### PR TITLE
Add option to remove layout cache from exports

### PR DESCRIPTION
**Pull request by OliverVahey**
This change is [Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65)

### CODE REVIEW

**Review by gilbertbw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65)* status: all files reviewed, 10 unresolved discussions (waiting on @OliverVahey)

*[a discussion](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbxfTL5UYKWotMGb3i:-MfbxfTL5UYKWotMGb3j:blb6xme) (no related file):*
As discussed you should try and determine what `LayoutCached...` does, and find a scenario where it has an impact.

---
___
*[Forms/Access SVN - Options.ACF, line 2691 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbsnJ-1a24ORZ3q98M:-MfbsnJ0-iKBgpY6o-cs:bggapmt) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Forms/Access SVN - Options.ACF#L2691)):*
> ```
>   DoCmd.Hourglass True
>   SetConfigValue "Remove GUIDs", True, Me.txtOutputLocation.Value
>   If CleanFormsReports(Me.txtOutputLocation.Value) Then
> ```

Why change this logic? If removing GUIDS failed, the user should review, and will probably want to rerun/debug.
___
*[Modules/modExtendSaveAsText.ACM, line 45 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-Mfburud4oDcRQceFlDN:-Mfburud4oDcRQceFlDO:brw4ve5) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L45)):*
> ```
> Private Declare Sub CopyMemory Lib "kernel32" Alias "RtlMoveMemory" (ByVal Destination As Any, ByVal Source As Any, ByVal Length As Long)
> 
> Private Function PopulateIgnoreArr(ByRef Ignores() As Ignore)
> ```

Add a note/full docstring, document what returning true and false means.
___
*[Modules/modExtendSaveAsText.ACM, line 54 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbulI064r_lzL8zQO7:-MfbulI064r_lzL8zQO8:b-80yqyk) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L54)):*
> ```
>   strExportPath = Application.Forms("Access SVN - Options").txtOutputLocation.Value
> 
>   blnIgnoreGUID = Nz(GetConfigValue("Remove GUIDs", strExportPath), False)
> ```

I'm not sure how I feel about this function 
___
*[Modules/modExtendSaveAsText.ACM, line 57 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-Mfbw2kaDGlsa19s2eRi:-Mfbw2kaDGlsa19s2eRj:b-nxzsfu) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L57)):*
> ```
>   blnIgnoreLayoutCache = Nz(GetConfigValue("Remove Layout Cache", strExportPath), False)
>   
>   lngArrayUbound = -1 ' Using minus one to represent empty, as cannot check if Ignores is empty, and 0 would mean 1 item.
> ```

Not sure if it's better, but can you take `IsArrayInitialised` from JCS? If your do this see https://github.com/x-ware-ltd/access-scc-addin/blob/8687a0e2f84d7701e92255c6eef2c01abaab72e2/Modules/xwFileFunctions%20-%20Partial.ACM for an example of how to structure.
___
*[Modules/modExtendSaveAsText.ACM, line 71 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbwWJg3qedF3obE0xE:-MfbwWJg3qedF3obE0xF:b-gc3avp) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L71)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>     If lngArrayUbound < 0 Then
> 
>       lngArrayUbound = 0
> 
>     Else
> 
>       lngArrayUbound = lngArrayUbound + 1
> 
>     End If
> ```
</details>


can just do `lngArrayUbound = lngArrayUbound + 1`, as `(-1) + 1  = 0`?
___
*[Modules/modExtendSaveAsText.ACM, line 75 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbtkOl3lmXIyYjM2p_:-MfbtkOl3lmXIyYjM2pa:bhtdoht) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L75)):*
> ```
>       lngArrayUbound = lngArrayUbound + 1
>     End If
>     ReDim Ignores(lngArrayUbound) As Ignore
> ```

Does this work? I think you need to redim preserve.

We should test it works with IgnoereGUID, IgnoreLayout, and both (IgnoreGUID and IgnoreLayout)
___
*[Modules/modExtendSaveAsText.ACM, line 82 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbwsUf3wXEkN_Jlf8v:-MfbwsUf3wXEkN_Jlf8w:b6ftskv) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L82)):*
> ```
> 
>   'Ignores(3).bytsStart = "PrtDevMode = Begin" & vbCrLf
>   'Ignores(3).bytsEnd = "End" & vbCrLf
> ```

nit. I thnk you can just delete these.
___
*[Modules/modExtendSaveAsText.ACM, line 108 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-Mfbx63V03ewXj2KZyGn:-Mfbx63V03ewXj2KZyGo:b-2nrqre) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L108)):*
> ```
> '************************************************
> 
> Public Sub SaveAsText(objType As asObjectType, objName As String, strFilename As String, enmEncode As asEncode)
> ```

I'd be tempted to pass `blnRemoveGUIDs` and `blnRemoveLayoutCached` into/through this function
___
*[Modules/modExtendSaveAsText.ACM, line 834 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbxKM1-0mTms5a35I9:-MfbxKM1-0mTms5a35IA:b98rye4) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L834)):*
> ```
>   sDelimiterOld = Chr(44)  '  ,
>   sSeperatorOld = Chr(34)  '  "
>   sDelimiter = Chr(135)    '  ‡
> ```

Not sure you should commit this, have you worked on this with a config file that UTF8 encodes the file?

**Review by OliverVahey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65)* status: all files reviewed, 9 unresolved discussions (waiting on @gilbertbw)

*[a discussion](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbxfTL5UYKWotMGb3i:-Mfm-csX0iYcA7U4FqVH:b-2pm2tb) (no related file):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

As discussed you should try and determine what `LayoutCached...` does, and find a scenario where it has an impact.
</blockquote></details>

I have spent a good amount of time on this, and i still am unsure of what this does. changing it manually on an exported form then importing it seems to have no noticeable effect. See my notes:

    Application.SaveAsText still undocumented, seems it has never had any.
    
    Anchor:
        anchor both:
            cached left and top seem to be idential to a control's uncached left and top.
            cached height and width are uncached top+height and left+width respectively.
    
        anchor left:
            cached left seem to be idential to a control's uncached left.
            cached width is uncached left+width.
        
        anchor top:
            cached top seem to be idential to a control's uncached top.
            cached height is uncached top+height.
    
        anchor right:
            cached left seem to be idential to a control's uncached left.
            cached width is uncached left+width.
        
        anchor bottom:
            cached top seem to be idential to a control's uncached top.
            cached height is uncached top+height.
    
        Unaffected by control anchor
    
    Form Orientation:
        No affect.
    
    Form Auto Resize: 
        No affect.
    
    Resizing Form:
        As long as the control is not move relative to the top left corner of the form, then it has     no affect.
    
    Export, manually change layout cache, import:
        no affect when opening the form. unless the control is moved, the layout cache will remain  as what it was manually changed to.
    
    Conclusion:
        This is a mystery, no idea what the hell it does. Potentially some sort of rendering    optimisation thing for the access front end? Pure speculation.
        Changing this value, or even deleting it completely, seems to have no affect on the form at     all.`

---
___
*[Forms/Access SVN - Options.ACF, line 2691 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbsnJ-1a24ORZ3q98M:-MflxgRNCddV4NTPE_Ai:bsrebvm) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Forms/Access SVN - Options.ACF#L2691)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

Why change this logic? If removing GUIDS failed, the user should review, and will probably want to rerun/debug.
</blockquote></details>

When manually running a sanitize, the config value is read by the PopulateIgnoreArr function, and would be false, thus not remove GUIDs which is obviously not what we want. If removing GUIDs fails halfway through it will be caught and the config value will be set to false. I do see what you mean though, and if you still want i can change it.
___
*[Modules/modExtendSaveAsText.ACM, line 45 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-Mfburud4oDcRQceFlDN:-Mfm-brN81fBPZguDX7K:b-896fix) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L45)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

Add a note/full docstring, document what returning true and false means.
</blockquote></details>

Done.
___
*[Modules/modExtendSaveAsText.ACM, line 54 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbulI064r_lzL8zQO7:-MfluQw75SbjrK5el9VH:blqd48o) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L54)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

I'm not sure how I feel about this function 
</blockquote></details>

Please elaborate.
___
*[Modules/modExtendSaveAsText.ACM, line 57 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-Mfbw2kaDGlsa19s2eRi:-Mflu5QN1EeESt9BgMnT:b-6swyua) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L57)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

Not sure if it's better, but can you take `IsArrayInitialised` from JCS? If your do this see https://github.com/x-ware-ltd/access-scc-addin/blob/8687a0e2f84d7701e92255c6eef2c01abaab72e2/Modules/xwFileFunctions%20-%20Partial.ACM for an example of how to structure.
</blockquote></details>

I assume you're reffering to IsArrayAllocated as IsArrayInitialised doesn't exist. I am unclear of what i am supposed to take from the link provide, could you please explain.
___
*[Modules/modExtendSaveAsText.ACM, line 71 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbwWJg3qedF3obE0xE:-MflSosKAF6l10gspOl_:blwt14a) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L71)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

> ```
>     If lngArrayUbound < 0 Then
> 
>       lngArrayUbound = 0
> 
>     Else
> 
>       lngArrayUbound = lngArrayUbound + 1
> 
>     End If
> ```

can just do `lngArrayUbound = lngArrayUbound + 1`, as `(-1) + 1  = 0`?
</blockquote></details>

Unclear, please explain.
___
*[Modules/modExtendSaveAsText.ACM, line 75 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbtkOl3lmXIyYjM2p_:-MflSoR55gT80HGCeOXs:b-naw63s) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L75)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

Does this work? I think you need to redim preserve.

We should test it works with IgnoereGUID, IgnoreLayout, and both (IgnoreGUID and IgnoreLayout)
</blockquote></details>

You're right, this was a problem, i have now corrected it. Done.
___
*[Modules/modExtendSaveAsText.ACM, line 82 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbwsUf3wXEkN_Jlf8v:-MflSuYvDVxnAzlJvDQJ:b-896fix) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L82)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

nit. I thnk you can just delete these.
</blockquote></details>

Done.
___
*[Modules/modExtendSaveAsText.ACM, line 108 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-Mfbx63V03ewXj2KZyGn:-MflSwRA1FU4AZVY5ylr:beepj67) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L108)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

I'd be tempted to pass `blnRemoveGUIDs` and `blnRemoveLayoutCached` into/through this function
</blockquote></details>

Would there be any reason? as we will may want on expand on PopulateIgnoreArr later, we would then need to pass more and more data through a function that doesn't use this data. If the flags are only used in one function, surely that's the place they should be read.
___
*[Modules/modExtendSaveAsText.ACM, line 834 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbxKM1-0mTms5a35I9:-MfluWay5OqGBrlinMYM:b2jk4n7) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L834)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

Not sure you should commit this, have you worked on this with a config file that UTF8 encodes the file?
</blockquote></details>

This was a mistake.

**Review by gilbertbw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65)* status: all files reviewed, 6 unresolved discussions (waiting on @OliverVahey)

*[a discussion](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbxfTL5UYKWotMGb3i:-MhIb8Pe-ftNhLirVdde:bgorm9a) (no related file):*
<details><summary><i>Previously, OliverVahey (Oliver Vahey) wrote…</i></summary><blockquote>

I have spent a good amount of time on this, and i still am unsure of what this does. changing it manually on an exported form then importing it seems to have no noticeable effect. See my notes:

    Application.SaveAsText still undocumented, seems it has never had any.
    
    Anchor:
        anchor both:
            cached left and top seem to be idential to a control's uncached left and top.
            cached height and width are uncached top+height and left+width respectively.
    
        anchor left:
            cached left seem to be idential to a control's uncached left.
            cached width is uncached left+width.
        
        anchor top:
            cached top seem to be idential to a control's uncached top.
            cached height is uncached top+height.
    
        anchor right:
            cached left seem to be idential to a control's uncached left.
            cached width is uncached left+width.
        
        anchor bottom:
            cached top seem to be idential to a control's uncached top.
            cached height is uncached top+height.
    
        Unaffected by control anchor
    
    Form Orientation:
        No affect.
    
    Form Auto Resize: 
        No affect.
    
    Resizing Form:
        As long as the control is not move relative to the top left corner of the form, then it has     no affect.
    
    Export, manually change layout cache, import:
        no affect when opening the form. unless the control is moved, the layout cache will remain  as what it was manually changed to.
    
    Conclusion:
        This is a mystery, no idea what the hell it does. Potentially some sort of rendering    optimisation thing for the access front end? Pure speculation.
        Changing this value, or even deleting it completely, seems to have no affect on the form at     all.`

</blockquote></details>

I have posed this question to the AUG.

---
___
*[Forms/Access SVN - Options.ACF, line 2691 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbsnJ-1a24ORZ3q98M:-MhIbN3zDvKbwmNZlzkW:b-lqp204) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Forms/Access SVN - Options.ACF#L2691)):*
<details><summary><i>Previously, OliverVahey (Oliver Vahey) wrote…</i></summary><blockquote>

When manually running a sanitize, the config value is read by the PopulateIgnoreArr function, and would be false, thus not remove GUIDs which is obviously not what we want. If removing GUIDs fails halfway through it will be caught and the config value will be set to false. I do see what you mean though, and if you still want i can change it.
</blockquote></details>

I think it's a bit hacky. This comes back to my suggestion than `PopulateIgnoreArr` not read the config file directly.
___
*[Modules/modExtendSaveAsText.ACM, line 54 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbulI064r_lzL8zQO7:-MhIb_9CAkhHmfba-N4N:b-h3zzwk) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L54)):*
<details><summary><i>Previously, OliverVahey (Oliver Vahey) wrote…</i></summary><blockquote>

Please elaborate.
</blockquote></details>

I think I meant to come back to this comment.
___
*[Modules/modExtendSaveAsText.ACM, line 57 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-Mfbw2kaDGlsa19s2eRi:-MhIbdLO4yTj3Yx9gCAE:b35qawx) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L57)):*
<details><summary><i>Previously, OliverVahey (Oliver Vahey) wrote…</i></summary><blockquote>

I assume you're reffering to IsArrayAllocated as IsArrayInitialised doesn't exist. I am unclear of what i am supposed to take from the link provide, could you please explain.
</blockquote></details>

I think you are right, I must have meant `IsArrayAllocated`. The link was just to give an example of how to name a module extracted from JCS.
___
*[Modules/modExtendSaveAsText.ACM, line 71 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbwWJg3qedF3obE0xE:-MhIbus1DG_5lBtRsI2-:bubjlc6) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L71)):*
<details><summary><i>Previously, OliverVahey (Oliver Vahey) wrote…</i></summary><blockquote>

Unclear, please explain.
</blockquote></details>

I think you can replace the quoted `If ... Else ... End If` (click the little > arrow on my original comment) with `lngArrayUbound = lngArrayUbound + 1`?
___
*[Modules/modExtendSaveAsText.ACM, line 108 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-Mfbx63V03ewXj2KZyGn:-MhIWo1R98Dd9U1uyzYF:b-bwxave) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L108)):*
<details><summary><i>Previously, OliverVahey (Oliver Vahey) wrote…</i></summary><blockquote>

Would there be any reason? as we will may want on expand on PopulateIgnoreArr later, we would then need to pass more and more data through a function that doesn't use this data. If the flags are only used in one function, surely that's the place they should be read.
</blockquote></details>

My thinking is that reading from the config file should be contained to the 'outer' layers of the application. The inner functions should be more self contained/we could use them in another application. `PopulateIgnoreArr` should not need to be aware of the config file/contain logic to decide what to ignore. Let's discuss further in person if you like.

**Review by OliverVahey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbertbw and @OliverVahey)

___
*[Forms/Access SVN - Options.ACF, line 2691 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbsnJ-1a24ORZ3q98M:-MhJY5B3CuPA3sF4oi6F:b-cs3hea) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Forms/Access SVN - Options.ACF#L2691)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

I think it's a bit hacky. This comes back to my suggestion than `PopulateIgnoreArr` not read the config file directly.
</blockquote></details>

Undone.
___
*[Modules/modExtendSaveAsText.ACM, line 54 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbulI064r_lzL8zQO7:-MhJ_Hpq9Iavbe3Q1bmE:b3ksm) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L54)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

I think I meant to come back to this comment.
</blockquote></details>

k
___
*[Modules/modExtendSaveAsText.ACM, line 57 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-Mfbw2kaDGlsa19s2eRi:-MhJaQuPDmIO0WSMkBak:bds41ya) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L57)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

I think you are right, I must have meant `IsArrayAllocated`. The link was just to give an example of how to name a module extracted from JCS.
</blockquote></details>

I think it is clearer how i have done it. We use functions returning booleans for success/failure in other places.
___
*[Modules/modExtendSaveAsText.ACM, line 71 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-MfbwWJg3qedF3obE0xE:-MhJZ9tIEnpHFJ0tNvOx:b4pljiu) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L71)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

I think you can replace the quoted `If ... Else ... End If` (click the little > arrow on my original comment) with `lngArrayUbound = lngArrayUbound + 1`?
</blockquote></details>

You're right. I'm not sure what i was thinking when i wrote that, possibly some logic from a previous iteration of this fix. Done.
___
*[Modules/modExtendSaveAsText.ACM, line 108 at r1](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/65#-Mfbx63V03ewXj2KZyGn:-MhJYLUF3OYimOcJ0m59:b-896fix) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/9d9d283731213ce6278fd719c42edc3448ddff31/Modules/modExtendSaveAsText.ACM#L108)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

My thinking is that reading from the config file should be contained to the 'outer' layers of the application. The inner functions should be more self contained/we could use them in another application. `PopulateIgnoreArr` should not need to be aware of the config file/contain logic to decide what to ignore. Let's discuss further in person if you like.
</blockquote></details>

Done.

**Pull request closed without merging**
