### PR TITLE
Support 64 bit Access

### LINKED ISSUE #10: 64-bit build?
```
What steps will reproduce the problem?
1. Try to start the add-in in Access 2013, 64-bit
2. Get error message, "The wizard you've requested is not installed or is in a 
bad state. Please install or reinstall the wizard. If you do not have 
permission to do this on your computer, please contact your help desk 
representative."

Running Access 2013, 64-bit, on Windows 8
```

Original issue reported on code.google.com by `tgmayfi...@gmail.com` on 12 Jun 2013 at 11:42

### PR DESCRIPTION
**Pull request by sfalla**
PR to support 64 bit Access
fixes #10 

- - -
This change is [Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69)

### CODE REVIEW

**Comment by sfalla** [comment]
Note that the change in modExtendSaveAsText is actually not 64 bit. It is to handle the new data types

**Review by gilbertbw — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69)* status: all files reviewed, 2 unresolved discussions (waiting on @sfalla)

___
*[`Modules/xwFileFunctions - Partial.ACM` line 38 at r3](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69#-NVUZL4J4lETobZv5mHV:-NVUZL4J4lETobZv5mHW:b-6p96zx) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/2f3c031b9594bb6b04f9441fcb1c495a74dbe756/Modules/xwFileFunctions%20-%20Partial.ACM#L38)):*
> ```
> ' @return String  The selected folder
> '************************************************
> Public Function BrowseFolderDialog(strTitle As String, InitialFileName As String) As String
> ```

Either
* We need to commit to adding this function into this file in JCS
* This function should be moved to a non-Partial file
* A comment needs to added to make it clear this function is not extracted from JCS
___
*[`Tables/USysReleaseHistory.ACT` line 266 at r3](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69#-NVUZ9C-76mCwj-vhO8x:-NVUZ9C08CCcena-4Nip:bvezy3r) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/2f3c031b9594bb6b04f9441fcb1c495a74dbe756/Tables/USysReleaseHistory.ACT#L266)):*
> ```
>         72� .72�#08/23/2021 00:00:00#��Fallback to finding references in Distributables�
>         73� .73�#08/04/2021 00:00:00#��Remove outdated startup msgbox�
>         74� .74�#05/05/2023 00:00:00#��Add support for 64-bit Office�
> ```

If you are updating the release history you need to include this change https://github.com/x-ware-ltd/access-scc-addin/commit/6384c74fbdbc797a0fb8ca57ffd768fd4ed00ff8

**Review by SWMahy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbertbw and @sfalla)

___
*[`Modules/xwFileFunctions - Partial.ACM` line 38 at r3](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69#-NVUZL4J4lETobZv5mHV:-NXPK9He0BWHR5ZtF2T0:b1dq79h) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/2f3c031b9594bb6b04f9441fcb1c495a74dbe756/Modules/xwFileFunctions%20-%20Partial.ACM#L38)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

Either
* We need to commit to adding this function into this file in JCS
* This function should be moved to a non-Partial file
* A comment needs to added to make it clear this function is not extracted from JCS
</blockquote></details>

@gilbertbw - did you change your mind on this?

**Review by SWMahy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @gilbertbw and @sfalla)

___
*[`Modules/xwFileFunctions - Partial.ACM` line 38 at r3](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69#-NVUZL4J4lETobZv5mHV:-NXnwI3A34p3HYXcLhzX:b-3dcmao) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/2f3c031b9594bb6b04f9441fcb1c495a74dbe756/Modules/xwFileFunctions%20-%20Partial.ACM#L38)):*
<details><summary><i>Previously, SWMahy (Steve Mahy) wrote…</i></summary><blockquote>

@gilbertbw - did you change your mind on this?
</blockquote></details>

Ok added comment

**Review by SWMahy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @gilbertbw)

___
*[`Tables/USysReleaseHistory.ACT` line 266 at r3](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69#-NVUZ9C-76mCwj-vhO8x:-NXymWt8DmK8ouhx39R2:btyy1o4) ([raw file](https://github.com/x-ware-ltd/access-scc-addin/blob/2f3c031b9594bb6b04f9441fcb1c495a74dbe756/Tables/USysReleaseHistory.ACT#L266)):*
<details><summary><i>Previously, gilbertbw (Gilbert Bishop-White) wrote…</i></summary><blockquote>

If you are updating the release history you need to include this change https://github.com/x-ware-ltd/access-scc-addin/commit/6384c74fbdbc797a0fb8ca57ffd768fd4ed00ff8
</blockquote></details>

ok - done

**Review by gilbertbw — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/x-ware-ltd/access-scc-addin/69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfalla)

**Pull request merged**
